name: OnPush _Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        description: "Select Environment"
        required: true
        default: "QA"
        type: choice
        options:
          - QA
          - Stage
          - Prod
      run_tests:
        description: "Run Automate Tests"
        required: false
        default: false
        type: boolean

      user:
        description: "Who is performing"
        required: true
        default: "NA"
        type: string

      iteration:
        description: "Which Iteration"
        required: true
        default: 0
        type: number
env:
  USER: test
  PASS: admin
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello world!"
      - name: Print Goodbye
        run: echo "Done - bye!"
  produce-txt:
    runs-on: ubuntu-latest
    steps:
      - name: Create a directory
        run: mkdir myfiles
      - name: Create first txt file
        run: |
          cd myfiles
          touch test1.txt
      - name: Create second txt file
        run: |
          cd myfiles
          touch test2.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Files
          path: myfiles

  Check-txt:
    needs: produce-txt
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Files
      - name: list files
        run: ls
  Check-user:
    needs: [produce-txt,Check-txt]
    runs-on: ubuntu-latest
    steps:
      - name: Print User
        run: echo "Hello ${{ env.USER }}"
      - name: Print Pass
        run: echo ${{ env.PASS}}

  check-envdetails:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment
        run: echo ${{ inputs.env }}
      - name: Check Test
        run: echo "Will Automated test run ${{ inputs.run_tests }}
      - name: check user
        run: echo "Hello ${{ inputs.user }}
      - name: check iteration
        run: echo "Iteration no ${{ inputs.iteration }}"