name: OnPush _Workflow
on: push
env:
  USER: test
  PASS: admin
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello world!"
      - name: Print Goodbye
        run: echo "Done - bye!"
  produce-txt:
    runs-on: ubuntu-latest
    steps:
      - name: Create a directory
        run: mkdir myfiles
      - name: Create first txt file
        run: |
          cd myfiles
          touch test1.txt
      - name: Create second txt file
        run: |
          cd myfiles
          touch test2.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Files
          path: myfiles

  Check-txt:
    needs: produce-txt
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Files
      - name: list files
        run: ls
  Check-user:
    needs: [produce-txt,Check-txt]
    runs-on: ubuntu-latest
    steps:
      - name: Print User
        run: echo "Hello ${{ env.USER }}"
      - name: Print Pass
        run: echo ${{ env.PASS}}
